export const DOWNLOAD_COINS = 'DOWNLOAD_COINS';
export const ADD_COIN_TO_PORTFOLIO = 'ADD_COIN_TO_PORTFOLIO';

export const REMOVE_COIN_FROM_PORTFOLIO = 'REMOVE_COIN_FROM_PORTFOLIO';
export const UPDATE_PORTFOLIOCOIN_COUNT = 'UPDATE_PORTFOLIOCOIN_COUNT';
export const UPDATE_PORTFOLIO_TOTALS = 'UPDATE_PORTFOLIO_TOTALS';

export const { UPDATE_USD_HOLDINGS } = 'UPDATE_USD_HOLDINGS';
export const { UPDATE_PERCENTAGE_HOLDINGS } = 'UPDATE_PERCENTAGE_HOLDINGS';
