export const DOWNLOAD_COINS = 'DOWNLOAD_COINS';
export const DOWNLOAD_COINS_PENDING = 'DOWNLOAD_COINS_PENDING';
export const DOWNLOAD_COINS_FULFILLED = 'DOWNLOAD_COINS_FULFILLED';

export const SET_PRICE_MARKERS = 'SET_PRICE_MARKERS';
export const UPDATE_SAVED_PORTFOLIO = 'UPDATE_SAVED_PORTFOLIO';
export const ADD_COIN_TO_PORTFOLIO = 'ADD_COIN_TO_PORTFOLIO';
export const REMOVE_COIN_FROM_PORTFOLIO = 'REMOVE_COIN_FROM_PORTFOLIO';
export const UPDATE_PORTFOLIOCOIN_COUNT = 'UPDATE_PORTFOLIOCOIN_COUNT';
export const UPDATE_PORTFOLIO_TOTALS = 'UPDATE_PORTFOLIO_TOTALS';
export const UPDATE_PORTFOLIO_PERCENTAGE = 'UPDATE_PORTFOLIO_PERCENTAGE';
export const CALCULATE_PORTFOLIO_TOTAL_PERCENTAGES = 'CALCULATE_PORTFOLIO_TOTAL_PERCENTAGES';
export const ADD_CUSTOM_COIN_TO_PORTFOLIO = 'ADD_CUSTOM_COIN_TO_PORTFOLIO';
export const UPDATE_CUSTOM_NAME = 'UPDATE_CUSTOM_NAME';
export const UPDATE_CUSTOM_BTC = 'UPDATE_CUSTOM_BTC';
export const UPDATE_CUSTOM_USD = 'UPDATE_CUSTOM_USD';
export const UPDATE_INDIVIDUAL_TOTALS = 'UPDATE_INDIVIDUAL_TOTALS';
export const SORTLIST = 'SORTLIST';
